[
	uuid(2F2330D4-7F62-491C-89A2-BBAC627AE2F8),
	version(1.0),
	helpstring("ResolveTo_1 Type Library")
]
library ResolveTo_1
{
   importlib("stdole2.tlb");
   importlib("stdole32.tlb");
   importlib("ResolveToRef.tlb");

   	[
		uuid(68e59b77-0fd8-4f3c-89d5-0efefd67af17)
	]
	interface IA:IDispatch
	{
		HRESULT method1(TargetType* param);
	};
};