[
  uuid(40da6a2b-cdf6-4940-a677-c8ac3aa2e31f),
  version(1.0)
]
library ConvertToOtherType_5
{
    importlib("stdole2.tlb");
    [
      uuid(65a7257f-2396-41cc-86b6-665f6641d07e)
    ]
    interface IA1 : IDispatch {
		HRESULT TargetFunction(int);
		HRESULT TargetFunction2(float);
		HRESULT TargetFunction3(BSTR);
    };
};
