import "oaidl.idl";
import "ocidl.idl";

[
	uuid(2F2330D4-7F62-491C-89A2-BBAC627AE2F8),
	version(1.0),
	helpstring("AddAttribute_4 Type Library")
]
library AddAttribute_4
{
   importlib("stdole2.tlb");
   importlib("stdole32.tlb");

   	[
		uuid(68e59b77-0fd8-4f3c-89d5-0efefd67af17)
	]
	interface TargetType:IDispatch{};

	[
		uuid(1c07d58e-b7f3-48be-b5e0-9c43c4b0b2a7)
	]
	interface TargetType2:IDispatch{};

	[
		uuid(5ee015c3-36fd-47cb-bc03-02bd10d38e3d)
	]
	dispinterface dispTargetType{};
};