[
	uuid(67c8367c-cf8f-4dcc-a56f-f20d2d6e1168),
	version(1.0),
	helpstring("ResolveTo_2 Type Library")
]
library ResolveTo_2
{
   importlib("stdole2.tlb");
   importlib("stdole32.tlb");
   importlib("ResolveToRef.tlb");

   	[
		uuid(68e59b77-0fd8-4f3c-89d5-0efefd67af17)
	]
	interface IA:IDispatch
	{
		HRESULT method1(TargetType* param, strTargetType* param2);
	};
};
